version: '3.8'

services:
  sqlite:
    build: ./sqlite
    environment:
      - SQLITE_DB_PATH=${SQLITE_DB_PATH}
      
    volumes:
      - ./sqlite:/app
      - ./sqlite:/data
    command: ["${SQLITE_DB_PATH}"]
